name: GitHub Pages
on:
  push:
    tags:
      - v*
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.x"
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Test
        run: go test -race ./...
        working-directory: ./demo
      - name: Build
        run: |
          GOARCH=wasm GOOS=js go build -o dist/web/app.wasm
          go run main.go -ssg=dist -prefix=budoux-go
        working-directory: ./demo
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./demo/dist
          force_orphan: true
