name: Test
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
permissions:
  contents: read
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.11.x, 1.x]
        platform: [ubuntu-latest]
    env:
      GO111MODULE: on
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: go test -race ./...
      - name: Test (demo)
        if: ${{ matrix.go-version == '1.x' }}
        run: go test -race ./...
        working-directory: ./demo
