name: TinyGo
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
permissions:
  contents: read
jobs:
  tinygo:
    strategy:
      matrix:
        go-version: ["1.17.x"]
        tinygo: ["0.22.0"]
        platform: [ubuntu-latest]
    env:
      GO111MODULE: on
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - uses: acifani/setup-tinygo@v1
        with:
          tinygo-version: ${{ matrix.tinygo }}
      - name: Test
        run: tinygo test .
      - name: Test (benchmark)
        run: tinygo test -bench .
